# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FenetrePrincipale.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1130, 635)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Onglets = QtWidgets.QTabWidget(self.centralwidget)
        self.Onglets.setGeometry(QtCore.QRect(10, 0, 1251, 581))
        self.Onglets.setObjectName("Onglets")
        self.SGBDAccess = QtWidgets.QWidget()
        self.SGBDAccess.setObjectName("SGBDAccess")
        self.frame_6 = QtWidgets.QFrame(self.SGBDAccess)
        self.frame_6.setGeometry(QtCore.QRect(160, 40, 621, 151))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_8 = QtWidgets.QLabel(self.frame_6)
        self.label_8.setGeometry(QtCore.QRect(20, 10, 341, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_6)
        self.label_9.setGeometry(QtCore.QRect(20, 40, 101, 16))
        self.label_9.setObjectName("label_9")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit.setGeometry(QtCore.QRect(130, 40, 141, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.checkBox = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox.setGeometry(QtCore.QRect(280, 40, 221, 17))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.AddPlace = QtWidgets.QPushButton(self.frame_6)
        self.AddPlace.setGeometry(QtCore.QRect(520, 40, 75, 23))
        self.AddPlace.setObjectName("AddPlace")
        self.label_11 = QtWidgets.QLabel(self.frame_6)
        self.label_11.setGeometry(QtCore.QRect(20, 80, 281, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.select_categorie = QtWidgets.QComboBox(self.frame_6)
        self.select_categorie.setGeometry(QtCore.QRect(50, 110, 151, 22))
        self.select_categorie.setObjectName("select_categorie")
        self.DelPlace = QtWidgets.QPushButton(self.frame_6)
        self.DelPlace.setGeometry(QtCore.QRect(270, 110, 75, 23))
        self.DelPlace.setObjectName("DelPlace")
        self.frame_2 = QtWidgets.QFrame(self.SGBDAccess)
        self.frame_2.setGeometry(QtCore.QRect(160, 240, 621, 71))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(20, 20, 341, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.ImportPlaces = QtWidgets.QPushButton(self.frame_2)
        self.ImportPlaces.setGeometry(QtCore.QRect(280, 20, 75, 23))
        self.ImportPlaces.setObjectName("ImportPlaces")
        self.Onglets.addTab(self.SGBDAccess, "")
        self.RawData = QtWidgets.QWidget()
        self.RawData.setObjectName("RawData")
        self.tableWidgetHistorique = QtWidgets.QTableWidget(self.RawData)
        self.tableWidgetHistorique.setGeometry(QtCore.QRect(230, 20, 711, 311))
        self.tableWidgetHistorique.setRowCount(20)
        self.tableWidgetHistorique.setObjectName("tableWidgetHistorique")
        self.tableWidgetHistorique.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHistorique.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHistorique.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHistorique.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHistorique.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHistorique.setHorizontalHeaderItem(4, item)
        self.tableWidgetHistorique.horizontalHeader().setHighlightSections(True)
        self.rappHebdoBtn = QtWidgets.QPushButton(self.RawData)
        self.rappHebdoBtn.setGeometry(QtCore.QRect(80, 390, 161, 23))
        self.rappHebdoBtn.setObjectName("rappHebdoBtn")
        self.rapMensuelBtn = QtWidgets.QPushButton(self.RawData)
        self.rapMensuelBtn.setGeometry(QtCore.QRect(340, 390, 161, 23))
        self.rapMensuelBtn.setObjectName("rapMensuelBtn")
        self.rapAnnuelBtn = QtWidgets.QPushButton(self.RawData)
        self.rapAnnuelBtn.setGeometry(QtCore.QRect(590, 390, 151, 23))
        self.rapAnnuelBtn.setObjectName("rapAnnuelBtn")
        self.frame = QtWidgets.QFrame(self.RawData)
        self.frame.setGeometry(QtCore.QRect(30, 80, 171, 161))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 10, 101, 16))
        self.label.setObjectName("label")
        self.horodateur = QtWidgets.QCheckBox(self.frame)
        self.horodateur.setGeometry(QtCore.QRect(10, 40, 101, 17))
        self.horodateur.setChecked(True)
        self.horodateur.setObjectName("horodateur")
        self.jaune = QtWidgets.QCheckBox(self.frame)
        self.jaune.setGeometry(QtCore.QRect(10, 60, 101, 17))
        self.jaune.setChecked(True)
        self.jaune.setObjectName("jaune")
        self.handicaped = QtWidgets.QCheckBox(self.frame)
        self.handicaped.setGeometry(QtCore.QRect(10, 80, 121, 17))
        self.handicaped.setChecked(True)
        self.handicaped.setObjectName("handicaped")
        self.optAffchgBtn = QtWidgets.QPushButton(self.frame)
        self.optAffchgBtn.setGeometry(QtCore.QRect(40, 120, 75, 23))
        self.optAffchgBtn.setObjectName("optAffchgBtn")
        self.rapGlobalBtn = QtWidgets.QPushButton(self.RawData)
        self.rapGlobalBtn.setGeometry(QtCore.QRect(830, 390, 151, 23))
        self.rapGlobalBtn.setObjectName("rapGlobalBtn")
        self.Onglets.addTab(self.RawData, "")
        self.GraphData = QtWidgets.QWidget()
        self.GraphData.setObjectName("GraphData")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.GraphData)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 10, 461, 251))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.GraphData)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(40, 290, 461, 241))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.GraphData)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(540, 10, 561, 531))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Onglets.addTab(self.GraphData, "")
        self.AnalyseAvancee = QtWidgets.QWidget()
        self.AnalyseAvancee.setObjectName("AnalyseAvancee")
        self.frame_4 = QtWidgets.QFrame(self.AnalyseAvancee)
        self.frame_4.setGeometry(QtCore.QRect(10, 20, 681, 151))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.filtreType = QtWidgets.QFrame(self.frame_4)
        self.filtreType.setGeometry(QtCore.QRect(30, 30, 171, 121))
        self.filtreType.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.filtreType.setFrameShadow(QtWidgets.QFrame.Raised)
        self.filtreType.setObjectName("filtreType")
        self.horodateur_2 = QtWidgets.QCheckBox(self.filtreType)
        self.horodateur_2.setGeometry(QtCore.QRect(10, 20, 101, 17))
        self.horodateur_2.setChecked(True)
        self.horodateur_2.setObjectName("horodateur_2")
        self.jaune_2 = QtWidgets.QCheckBox(self.filtreType)
        self.jaune_2.setGeometry(QtCore.QRect(10, 40, 101, 17))
        self.jaune_2.setChecked(True)
        self.jaune_2.setObjectName("jaune_2")
        self.handicaped_2 = QtWidgets.QCheckBox(self.filtreType)
        self.handicaped_2.setGeometry(QtCore.QRect(10, 60, 121, 17))
        self.handicaped_2.setChecked(True)
        self.handicaped_2.setObjectName("handicaped_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_4)
        self.frame_3.setGeometry(QtCore.QRect(230, 30, 171, 111))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 117, 20))
        self.label_3.setObjectName("label_3")
        self.datemin = QtWidgets.QDateEdit(self.frame_3)
        self.datemin.setGeometry(QtCore.QRect(20, 30, 119, 20))
        self.datemin.setObjectName("datemin")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(20, 60, 109, 19))
        self.label_4.setObjectName("label_4")
        self.datemax = QtWidgets.QDateEdit(self.frame_3)
        self.datemax.setGeometry(QtCore.QRect(20, 90, 119, 20))
        self.datemax.setObjectName("datemax")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setGeometry(QtCore.QRect(430, 20, 221, 121))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.Somme = QtWidgets.QCheckBox(self.frame_5)
        self.Somme.setGeometry(QtCore.QRect(10, 20, 70, 17))
        self.Somme.setChecked(True)
        self.Somme.setObjectName("Somme")
        self.Moyenne = QtWidgets.QCheckBox(self.frame_5)
        self.Moyenne.setGeometry(QtCore.QRect(10, 50, 70, 17))
        self.Moyenne.setChecked(True)
        self.Moyenne.setObjectName("Moyenne")
        self.Variance = QtWidgets.QCheckBox(self.frame_5)
        self.Variance.setGeometry(QtCore.QRect(10, 80, 70, 17))
        self.Variance.setChecked(True)
        self.Variance.setObjectName("Variance")
        self.Minimum = QtWidgets.QCheckBox(self.frame_5)
        self.Minimum.setGeometry(QtCore.QRect(130, 20, 70, 17))
        self.Minimum.setChecked(True)
        self.Minimum.setObjectName("Minimum")
        self.Maximum = QtWidgets.QCheckBox(self.frame_5)
        self.Maximum.setGeometry(QtCore.QRect(130, 50, 70, 17))
        self.Maximum.setChecked(True)
        self.Maximum.setObjectName("Maximum")
        self.Etendue = QtWidgets.QCheckBox(self.frame_5)
        self.Etendue.setGeometry(QtCore.QRect(130, 80, 70, 17))
        self.Etendue.setChecked(True)
        self.Etendue.setObjectName("Etendue")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setGeometry(QtCore.QRect(470, 10, 61, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setGeometry(QtCore.QRect(260, 10, 81, 16))
        self.label_6.setObjectName("label_6")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setGeometry(QtCore.QRect(50, 10, 101, 16))
        self.label_2.setObjectName("label_2")
        self.calculsTable = QtWidgets.QTableWidget(self.AnalyseAvancee)
        self.calculsTable.setGeometry(QtCore.QRect(70, 210, 451, 311))
        self.calculsTable.setObjectName("calculsTable")
        self.calculsTable.setColumnCount(0)
        self.calculsTable.setRowCount(0)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.AnalyseAvancee)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(640, 210, 461, 311))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.calcul_layout_graph = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.calcul_layout_graph.setContentsMargins(0, 0, 0, 0)
        self.calcul_layout_graph.setObjectName("calcul_layout_graph")
        self.Use_Montants = QtWidgets.QComboBox(self.AnalyseAvancee)
        self.Use_Montants.setGeometry(QtCore.QRect(880, 180, 171, 22))
        self.Use_Montants.setObjectName("Use_Montants")
        self.Use_Montants.addItem("")
        self.Use_Montants.addItem("")
        self.label_7 = QtWidgets.QLabel(self.AnalyseAvancee)
        self.label_7.setGeometry(QtCore.QRect(690, 180, 171, 16))
        self.label_7.setObjectName("label_7")
        self.Calculer = QtWidgets.QPushButton(self.AnalyseAvancee)
        self.Calculer.setGeometry(QtCore.QRect(720, 80, 75, 23))
        self.Calculer.setObjectName("Calculer")
        self.Onglets.addTab(self.AnalyseAvancee, "")
        self.anomalies = QtWidgets.QWidget()
        self.anomalies.setObjectName("anomalies")
        self.pannes_table = QtWidgets.QTableWidget(self.anomalies)
        self.pannes_table.setGeometry(QtCore.QRect(90, 150, 921, 192))
        self.pannes_table.setObjectName("pannes_table")
        self.pannes_table.setColumnCount(0)
        self.pannes_table.setRowCount(0)
        self.ScanAnomalies = QtWidgets.QPushButton(self.anomalies)
        self.ScanAnomalies.setGeometry(QtCore.QRect(330, 60, 421, 23))
        self.ScanAnomalies.setObjectName("ScanAnomalies")
        self.label_12 = QtWidgets.QLabel(self.anomalies)
        self.label_12.setGeometry(QtCore.QRect(110, 110, 401, 16))
        self.label_12.setObjectName("label_12")
        self.Onglets.addTab(self.anomalies, "")
        self.Help = QtWidgets.QWidget()
        self.Help.setObjectName("Help")
        self.textBrowser = QtWidgets.QTextBrowser(self.Help)
        self.textBrowser.setGeometry(QtCore.QRect(220, 110, 581, 331))
        self.textBrowser.setObjectName("textBrowser")
        self.Onglets.addTab(self.Help, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1130, 21))
        self.menubar.setObjectName("menubar")
        self.menuRaw_Data = QtWidgets.QMenu(self.menubar)
        self.menuRaw_Data.setObjectName("menuRaw_Data")
        self.menuAide = QtWidgets.QMenu(self.menubar)
        self.menuAide.setObjectName("menuAide")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionDonn_es_brutes = QtWidgets.QAction(MainWindow)
        self.actionDonn_es_brutes.setObjectName("actionDonn_es_brutes")
        self.actionDonn_es_Graphiques = QtWidgets.QAction(MainWindow)
        self.actionDonn_es_Graphiques.setObjectName("actionDonn_es_Graphiques")
        self.actionQuitter = QtWidgets.QAction(MainWindow)
        self.actionQuitter.setObjectName("actionQuitter")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.menuRaw_Data.addAction(self.actionQuitter)
        self.menuAide.addAction(self.action)
        self.menubar.addAction(self.menuRaw_Data.menuAction())
        self.menubar.addAction(self.menuAide.menuAction())

        self.retranslateUi(MainWindow)
        self.Onglets.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Smart Parking Data Analysis Tool"))
        self.Onglets.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Historique en vue graphique</p></body></html>"))
        self.Onglets.setAccessibleName(_translate("MainWindow", "Données graphiques"))
        self.label_8.setText(_translate("MainWindow", "Ajouter une nouvelle catégorie de parkings :"))
        self.label_9.setText(_translate("MainWindow", "Nom de la catégorie:"))
        self.checkBox.setText(_translate("MainWindow", "Toutes les places appartiennent à cette catégorie"))
        self.AddPlace.setText(_translate("MainWindow", "Ajouter"))
        self.label_11.setText(_translate("MainWindow", "Séléctionnez une catégorie à supprimer:"))
        self.DelPlace.setText(_translate("MainWindow", "Supprimer"))
        self.label_10.setText(_translate("MainWindow", "Importer une liste de places de parking :"))
        self.ImportPlaces.setText(_translate("MainWindow", "Import..."))
        self.Onglets.setTabText(self.Onglets.indexOf(self.SGBDAccess), _translate("MainWindow", "Gestion de la Base de données"))
        self.RawData.setWhatsThis(_translate("MainWindow", "Historique en vue tabulaire"))
        self.RawData.setAccessibleName(_translate("MainWindow", "Données Brutes"))
        item = self.tableWidgetHistorique.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id entrée"))
        item = self.tableWidgetHistorique.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Heure début"))
        item = self.tableWidgetHistorique.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Heure fin"))
        item = self.tableWidgetHistorique.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Id Place"))
        item = self.tableWidgetHistorique.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Montant payé"))
        self.rappHebdoBtn.setText(_translate("MainWindow", "Rapport hebdomadaire"))
        self.rapMensuelBtn.setText(_translate("MainWindow", "Rapport mensuel"))
        self.rapAnnuelBtn.setText(_translate("MainWindow", "Rapport annuel"))
        self.label.setText(_translate("MainWindow", "Options d\'affichage"))
        self.horodateur.setText(_translate("MainWindow", "      Horodateur"))
        self.jaune.setText(_translate("MainWindow", "          Jaune"))
        self.handicaped.setText(_translate("MainWindow", "    Espace  handicapé"))
        self.optAffchgBtn.setText(_translate("MainWindow", "OK"))
        self.rapGlobalBtn.setText(_translate("MainWindow", "Rapport global"))
        self.Onglets.setTabText(self.Onglets.indexOf(self.RawData), _translate("MainWindow", "Données brutes"))
        self.Onglets.setTabText(self.Onglets.indexOf(self.GraphData), _translate("MainWindow", "Affichage graphique global"))
        self.horodateur_2.setText(_translate("MainWindow", "      Horodateur"))
        self.jaune_2.setText(_translate("MainWindow", "          Jaune"))
        self.handicaped_2.setText(_translate("MainWindow", "    Espace  handicapé"))
        self.label_3.setText(_translate("MainWindow", "De:"))
        self.label_4.setText(_translate("MainWindow", "À:"))
        self.Somme.setText(_translate("MainWindow", "Somme"))
        self.Moyenne.setText(_translate("MainWindow", "Moyenne"))
        self.Variance.setText(_translate("MainWindow", "Variance"))
        self.Minimum.setText(_translate("MainWindow", "Minimum"))
        self.Maximum.setText(_translate("MainWindow", "Maximum"))
        self.Etendue.setText(_translate("MainWindow", "Etendue"))
        self.label_5.setText(_translate("MainWindow", "Fonctions:"))
        self.label_6.setText(_translate("MainWindow", "Plage de dates:"))
        self.label_2.setText(_translate("MainWindow", "Type de places:"))
        self.Use_Montants.setItemText(0, _translate("MainWindow", "Utilisations"))
        self.Use_Montants.setItemText(1, _translate("MainWindow", "Montants"))
        self.label_7.setText(_translate("MainWindow", "Affichage des :"))
        self.Calculer.setText(_translate("MainWindow", "Ok"))
        self.Onglets.setTabText(self.Onglets.indexOf(self.AnalyseAvancee), _translate("MainWindow", "Calculs Avancés"))
        self.ScanAnomalies.setText(_translate("MainWindow", "Lancer un scan"))
        self.label_12.setText(_translate("MainWindow", "Senseurs avec comportement aberrant:"))
        self.Onglets.setTabText(self.Onglets.indexOf(self.anomalies), _translate("MainWindow", "Détection d\'anomalies"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Ceci est un outil conçu spécialement pour le parking intelligent de l\'Université de Sherbrooke.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Le premier onglet comporte un affichage des données brutes de l\'historique de l\'utilisation de l\'application, et offre la possibilité de générer des rapports pour les sept derniers jours, les 30 derniers jours et l\'an passé.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Le deuxième onglet est un affichage graphique pour ces données, permettant donc d\'avoir une vue globale sur différents indicateurs.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Pour plus d\'informations concernant l\'UdeS : </span><a href=\"www.usherbrooke.ca\"><span style=\" font-size:14pt; text-decoration: underline; color:#0000ff;\">www.usherbrooke.ca</span></a></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Pour le code source de l\'application : <br /></span><a href=\"https://github.com/afaf-taik/Smart-Parking-Data-Analysis\"><span style=\" font-size:14pt; text-decoration: underline; color:#0000ff;\">https://github.com/afaf-taik/Smart-Parking-Data-Analysis</span></a><span style=\" font-size:12pt;\"><br /></span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Requirements pour faire marcher le code: <br />jinja2, pdfkit , cassandra-driver, PyQt5, pandas. <br /></span></p></body></html>"))
        self.Onglets.setTabText(self.Onglets.indexOf(self.Help), _translate("MainWindow", "?"))
        self.menuRaw_Data.setTitle(_translate("MainWindow", "Options"))
        self.menuAide.setTitle(_translate("MainWindow", "Aide"))
        self.actionDonn_es_brutes.setText(_translate("MainWindow", "Données brutes"))
        self.actionDonn_es_Graphiques.setText(_translate("MainWindow", "Données Graphiques"))
        self.actionQuitter.setText(_translate("MainWindow", "Quitter"))
        self.action.setText(_translate("MainWindow", "?"))

