# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FenetrePrincipale.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Onglets = QtWidgets.QTabWidget(self.centralwidget)
        self.Onglets.setGeometry(QtCore.QRect(0, 0, 791, 551))
        self.Onglets.setObjectName("Onglets")
        self.RawData = QtWidgets.QWidget()
        self.RawData.setObjectName("RawData")
        self.tableWidgetHistorique = QtWidgets.QTableWidget(self.RawData)
        self.tableWidgetHistorique.setGeometry(QtCore.QRect(230, 20, 511, 311))
        self.tableWidgetHistorique.setRowCount(20)
        self.tableWidgetHistorique.setObjectName("tableWidgetHistorique")
        self.tableWidgetHistorique.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHistorique.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHistorique.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHistorique.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHistorique.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHistorique.setHorizontalHeaderItem(4, item)
        self.tableWidgetHistorique.horizontalHeader().setHighlightSections(True)
        self.rappHebdoBtn = QtWidgets.QPushButton(self.RawData)
        self.rappHebdoBtn.setGeometry(QtCore.QRect(80, 390, 161, 23))
        self.rappHebdoBtn.setObjectName("rappHebdoBtn")
        self.rapMensuelBtn = QtWidgets.QPushButton(self.RawData)
        self.rapMensuelBtn.setGeometry(QtCore.QRect(340, 390, 161, 23))
        self.rapMensuelBtn.setObjectName("rapMensuelBtn")
        self.rapAnnuelBtn = QtWidgets.QPushButton(self.RawData)
        self.rapAnnuelBtn.setGeometry(QtCore.QRect(590, 390, 141, 23))
        self.rapAnnuelBtn.setObjectName("rapAnnuelBtn")
        self.frame = QtWidgets.QFrame(self.RawData)
        self.frame.setGeometry(QtCore.QRect(30, 80, 171, 161))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 10, 101, 16))
        self.label.setObjectName("label")
        self.horodateur = QtWidgets.QCheckBox(self.frame)
        self.horodateur.setGeometry(QtCore.QRect(10, 40, 101, 17))
        self.horodateur.setChecked(True)
        self.horodateur.setObjectName("horodateur")
        self.jaune = QtWidgets.QCheckBox(self.frame)
        self.jaune.setGeometry(QtCore.QRect(10, 60, 101, 17))
        self.jaune.setChecked(True)
        self.jaune.setObjectName("jaune")
        self.handicaped = QtWidgets.QCheckBox(self.frame)
        self.handicaped.setGeometry(QtCore.QRect(10, 80, 121, 17))
        self.handicaped.setChecked(True)
        self.handicaped.setObjectName("handicaped")
        self.optAffchgBtn = QtWidgets.QPushButton(self.frame)
        self.optAffchgBtn.setGeometry(QtCore.QRect(40, 120, 75, 23))
        self.optAffchgBtn.setObjectName("optAffchgBtn")
        self.Onglets.addTab(self.RawData, "")
        self.GraphData = QtWidgets.QWidget()
        self.GraphData.setObjectName("GraphData")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.GraphData)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(270, 10, 461, 231))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.GraphData)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(270, 270, 461, 241))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.GraphData)
        self.label_2.setGeometry(QtCore.QRect(130, 30, 91, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.GraphData)
        self.label_3.setGeometry(QtCore.QRect(130, 320, 111, 20))
        self.label_3.setObjectName("label_3")
        self.freqAffichList = QtWidgets.QComboBox(self.GraphData)
        self.freqAffichList.setGeometry(QtCore.QRect(40, 230, 131, 22))
        self.freqAffichList.setObjectName("freqAffichList")
        self.freqAffichList.addItem("")
        self.freqAffichList.addItem("")
        self.freqAffichList.addItem("")
        self.freqAffichList.addItem("")
        self.label_4 = QtWidgets.QLabel(self.GraphData)
        self.label_4.setGeometry(QtCore.QRect(20, 200, 141, 16))
        self.label_4.setObjectName("label_4")
        self.Onglets.addTab(self.GraphData, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidgetEmplacement = QtWidgets.QTableWidget(self.tab)
        self.tableWidgetEmplacement.setGeometry(QtCore.QRect(160, 50, 471, 351))
        self.tableWidgetEmplacement.setObjectName("tableWidgetEmplacement")
        self.tableWidgetEmplacement.setColumnCount(3)
        self.tableWidgetEmplacement.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEmplacement.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEmplacement.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEmplacement.setHorizontalHeaderItem(2, item)
        self.Onglets.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuRaw_Data = QtWidgets.QMenu(self.menubar)
        self.menuRaw_Data.setObjectName("menuRaw_Data")
        self.menuAide = QtWidgets.QMenu(self.menubar)
        self.menuAide.setObjectName("menuAide")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionDonn_es_brutes = QtWidgets.QAction(MainWindow)
        self.actionDonn_es_brutes.setObjectName("actionDonn_es_brutes")
        self.actionDonn_es_Graphiques = QtWidgets.QAction(MainWindow)
        self.actionDonn_es_Graphiques.setObjectName("actionDonn_es_Graphiques")
        self.actionQuitter = QtWidgets.QAction(MainWindow)
        self.actionQuitter.setObjectName("actionQuitter")
        self.menuRaw_Data.addAction(self.actionQuitter)
        self.menubar.addAction(self.menuRaw_Data.menuAction())
        self.menubar.addAction(self.menuAide.menuAction())

        self.retranslateUi(MainWindow)
        self.Onglets.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Smart Parking Data Analysis Tool"))
        self.Onglets.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Historique en vue graphique</p></body></html>"))
        self.Onglets.setAccessibleName(_translate("MainWindow", "Données graphiques"))
        self.RawData.setWhatsThis(_translate("MainWindow", "Historique en vue tabulaire"))
        self.RawData.setAccessibleName(_translate("MainWindow", "Données Brutes"))
        item = self.tableWidgetHistorique.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id entrée"))
        item = self.tableWidgetHistorique.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Heure début"))
        item = self.tableWidgetHistorique.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Heure fin"))
        item = self.tableWidgetHistorique.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Id Place"))
        item = self.tableWidgetHistorique.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Montant payé"))
        self.rappHebdoBtn.setText(_translate("MainWindow", "Rapport hebdomadaire"))
        self.rapMensuelBtn.setText(_translate("MainWindow", "Rapport mensuel"))
        self.rapAnnuelBtn.setText(_translate("MainWindow", "Rapport annuel"))
        self.label.setText(_translate("MainWindow", "Options d\'affichage"))
        self.horodateur.setText(_translate("MainWindow", "      Horodateur"))
        self.jaune.setText(_translate("MainWindow", "          Jaune"))
        self.handicaped.setText(_translate("MainWindow", "    Espace  handicapé"))
        self.optAffchgBtn.setText(_translate("MainWindow", "OK"))
        self.Onglets.setTabText(self.Onglets.indexOf(self.RawData), _translate("MainWindow", "Données brutes"))
        self.label_2.setText(_translate("MainWindow", "Montants payés:"))
        self.label_3.setText(_translate("MainWindow", "Nombre d\'utilisations:"))
        self.freqAffichList.setProperty("currentText", _translate("MainWindow", "Par heure"))
        self.freqAffichList.setItemText(0, _translate("MainWindow", "Par heure"))
        self.freqAffichList.setItemText(1, _translate("MainWindow", "Hebdomadaire"))
        self.freqAffichList.setItemText(2, _translate("MainWindow", "Mensuel"))
        self.freqAffichList.setItemText(3, _translate("MainWindow", "Annuel"))
        self.label_4.setText(_translate("MainWindow", "Frequence de l\'affichage:"))
        self.Onglets.setTabText(self.Onglets.indexOf(self.GraphData), _translate("MainWindow", "Affichage graphique global"))
        item = self.tableWidgetEmplacement.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Lieu"))
        item = self.tableWidgetEmplacement.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "N. utilisations"))
        item = self.tableWidgetEmplacement.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Total paiements"))
        self.Onglets.setTabText(self.Onglets.indexOf(self.tab), _translate("MainWindow", "Statistiques par emplacement"))
        self.menuRaw_Data.setTitle(_translate("MainWindow", "Options"))
        self.menuAide.setTitle(_translate("MainWindow", "Aide"))
        self.actionDonn_es_brutes.setText(_translate("MainWindow", "Données brutes"))
        self.actionDonn_es_Graphiques.setText(_translate("MainWindow", "Données Graphiques"))
        self.actionQuitter.setText(_translate("MainWindow", "Quitter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

