# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from cassandra.cluster import Cluster

class Ui_MainWindow(object):
     def load_data(self,table):
        cluster= Cluster()
        session= cluster.connect()
        session.set_keyspace('smartparking')
        rows = session.execute("select * from historique;")
        data=list(rows)
        self._set_table_entries(table, data)
        
     def _set_table_entries(self, table, data):
        """
            Set table data from list
        """
        if data:
            table.setRowCount(len(data))
            table.setColumnCount(len(data[0]))

            for i in range(len(data)):
                for j in range(len(data[0])):
                    table.setItem(i, j, QtWidgets.QTableWidgetItem(str(data[i][j])))
        else:
            table.setRowCount(0)

     def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 776)
        self.main_widget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_widget.sizePolicy().hasHeightForWidth())
        self.main_widget.setSizePolicy(sizePolicy)
        self.main_widget.setObjectName("main_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_tab_widget = QtWidgets.QTabWidget(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_tab_widget.sizePolicy().hasHeightForWidth())
        self.main_tab_widget.setSizePolicy(sizePolicy)
        self.main_tab_widget.setObjectName("main_tab_widget")
        self.NumbersTalk = QtWidgets.QWidget()
        self.NumbersTalk.setObjectName("NumbersTalk")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.NumbersTalk)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 1081, 681))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.Statistics = QtWidgets.QTabWidget(self.verticalLayoutWidget_4)
        self.Statistics.setObjectName("Statistics")
        self.data_import = QtWidgets.QWidget()
        self.data_import.setObjectName("data_import")
        self.but_import = QtWidgets.QPushButton(self.data_import)
        self.but_import.setGeometry(QtCore.QRect(920, 590, 111, 29))
        self.but_import.setObjectName("but_import")
        self.data_preview_tab = QtWidgets.QTableWidget(self.data_import)
        self.data_preview_tab.setGeometry(QtCore.QRect(30, 20, 1021, 481))
        self.data_preview_tab.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.data_preview_tab.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.data_preview_tab.setObjectName("data_preview_tab")
        self.data_preview_tab.setColumnCount(10)
        self.data_preview_tab.setRowCount(70)
        self.load_data(self.data_preview_tab)
        self.Statistics.addTab(self.data_import, "")
        self.park_categories = QtWidgets.QWidget()
        self.park_categories.setObjectName("park_categories")
        self.park_category_aliases_tab = QtWidgets.QTableWidget(self.park_categories)
        self.park_category_aliases_tab.setGeometry(QtCore.QRect(10, 10, 351, 441))
        self.park_category_aliases_tab.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.park_category_aliases_tab.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.park_category_aliases_tab.setObjectName("park_category_aliases_tab")
        self.park_category_aliases_tab.setColumnCount(0)
        self.park_category_aliases_tab.setRowCount(0)
        self.park_categories_tab = QtWidgets.QTableWidget(self.park_categories)
        self.park_categories_tab.setGeometry(QtCore.QRect(370, 10, 691, 441))
        self.park_categories_tab.setObjectName("park_categories_tab")
        self.park_categories_tab.setColumnCount(0)
        self.park_categories_tab.setRowCount(0)
        self.park_categories_unknown_tab = QtWidgets.QTableWidget(self.park_categories)
        self.park_categories_unknown_tab.setGeometry(QtCore.QRect(10, 460, 1051, 171))
        self.park_categories_unknown_tab.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.park_categories_unknown_tab.setObjectName("park_categories_unknown_tab")
        self.park_categories_unknown_tab.setColumnCount(0)
        self.park_categories_unknown_tab.setRowCount(0)
        self.Statistics.addTab(self.park_categories, "")
        self.verticalLayout_8.addWidget(self.Statistics)
        self.main_tab_widget.addTab(self.NumbersTalk, "")
        self.overview_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overview_tab.sizePolicy().hasHeightForWidth())
        self.overview_tab.setSizePolicy(sizePolicy)
        self.overview_tab.setObjectName("overview_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.overview_tab)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.money_graph_hbox = QtWidgets.QHBoxLayout()
        self.money_graph_hbox.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.money_graph_hbox.setObjectName("money_graph_hbox")
        self.verticalLayout.addLayout(self.money_graph_hbox)
        self.counting_graph_hbox = QtWidgets.QHBoxLayout()
        self.counting_graph_hbox.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.counting_graph_hbox.setObjectName("counting_graph_hbox")
        self.verticalLayout.addLayout(self.counting_graph_hbox)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.main_tab_widget.addTab(self.overview_tab, "")
        self.days_tab = QtWidgets.QWidget()
        self.days_tab.setObjectName("days_tab")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.days_tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1071, 691))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.days_main_tab = QtWidgets.QTabWidget(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.days_main_tab.sizePolicy().hasHeightForWidth())
        self.days_main_tab.setSizePolicy(sizePolicy)
        self.days_main_tab.setTabPosition(QtWidgets.QTabWidget.North)
        self.days_main_tab.setObjectName("days_main_tab")
        self.Overall_Parkings = QtWidgets.QWidget()
        self.Overall_Parkings.setObjectName("Overall_Parkings")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Overall_Parkings)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.day_expenses_vbox = QtWidgets.QVBoxLayout()
        self.day_expenses_vbox.setObjectName("day_expenses_vbox")
        self.horizontalLayout_2.addLayout(self.day_expenses_vbox)
        self.days_main_tab.addTab(self.Overall_Parkings, "")
        self.money_tab = QtWidgets.QWidget()
        self.money_tab.setObjectName("money_tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.money_tab)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.money_vbox = QtWidgets.QVBoxLayout()
        self.money_vbox.setObjectName("money_vbox")
        self.verticalLayout_5.addLayout(self.money_vbox)
        self.days_main_tab.addTab(self.money_tab, "")
        self.horizontalLayout_5.addWidget(self.days_main_tab)
        self.main_tab_widget.addTab(self.days_tab, "")
        self.Locations_tab = QtWidgets.QWidget()
        self.Locations_tab.setObjectName("Locations_tab")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.Locations_tab)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, 1071, 691))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.single_locations_container = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.single_locations_container.setContentsMargins(0, 0, 0, 0)
        self.single_locations_container.setObjectName("single_locations_container")
        self.main_tab_widget.addTab(self.Locations_tab, "")
        self.search_tab = QtWidgets.QWidget()
        self.search_tab.setObjectName("search_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.search_tab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setContentsMargins(500, -1, -1, -1)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label = QtWidgets.QLabel(self.search_tab)
        self.label.setObjectName("label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.search_field = QtWidgets.QLineEdit(self.search_tab)
        self.search_field.setObjectName("search_field")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.search_field)
        self.verticalLayout_3.addLayout(self.formLayout_3)
        self.search_results = QtWidgets.QTableWidget(self.search_tab)
        self.search_results.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.search_results.setObjectName("search_results")
        self.search_results.setColumnCount(0)
        self.search_results.setRowCount(0)
        self.verticalLayout_3.addWidget(self.search_results)
        self.main_tab_widget.addTab(self.search_tab, "")
        self.horizontalLayout.addWidget(self.main_tab_widget)
        MainWindow.setCentralWidget(self.main_widget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.main_tab_widget.setCurrentIndex(0)
        self.Statistics.setCurrentIndex(0)
        self.days_main_tab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

     def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Smart Parking Data Analysis"))
        self.but_import.setText(_translate("MainWindow", "Import"))
        self.Statistics.setTabText(self.Statistics.indexOf(self.data_import), _translate("MainWindow", "Statistics"))
        self.park_category_aliases_tab.setSortingEnabled(False)
        self.park_categories_tab.setSortingEnabled(False)
        self.Statistics.setTabText(self.Statistics.indexOf(self.park_categories), _translate("MainWindow", "Manage categories"))
        self.main_tab_widget.setTabText(self.main_tab_widget.indexOf(self.NumbersTalk), _translate("MainWindow", "Numbers Talk"))
        self.main_tab_widget.setTabText(self.main_tab_widget.indexOf(self.overview_tab), _translate("MainWindow", "Overview"))
        self.days_main_tab.setTabText(self.days_main_tab.indexOf(self.Overall_Parkings), _translate("MainWindow", "Stationnements"))
        self.days_main_tab.setTabText(self.days_main_tab.indexOf(self.money_tab), _translate("MainWindow", "Payments"))
        self.main_tab_widget.setTabText(self.main_tab_widget.indexOf(self.days_tab), _translate("MainWindow", "Days"))
        self.main_tab_widget.setTabText(self.main_tab_widget.indexOf(self.Locations_tab), _translate("MainWindow", "Locations"))
        self.label.setText(_translate("MainWindow", "Search"))
        self.search_results.setSortingEnabled(True)
        self.main_tab_widget.setTabText(self.main_tab_widget.indexOf(self.search_tab), _translate("MainWindow", "Search"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

